### ISSUE TITLE
Impossible scrolling in the about page

### ISSUE THREAD

**Issue by Kratacoa** [essentialbooks/books#36]
As per title, it is impossible to scroll on the page , which might prove necessary on devices with small resolution. I haven't noticed the issue in the books themselves (so far I've checked the ones on Javascript and Go) .
The link to the page I'm referring to is https://www.programming-books.io/about , my browser is Firefox v. 66.0.2 .

**Comment by kjk** [comment]
Thanks for letting me know, should be fixed.

**Comment by Kratacoa** [comment]
> Thanks for letting me know, should be fixed.

Thank you, the scroll works now, but for some reason the last paragraph (__We also add...__) is still not visible on my Thinkpad X240.

**Comment by kjk** [comment]
Thanks, I tweaked it again, hopefully fixing that too.
